name: PS2 Build

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-ps2:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          apk update && apk add --no-cache build-base git

      - name: Compile CPS2emu
        # This tells GitHub to run the following commands inside the 'src' folder
        working-directory: ./src
        run: |
          make clean
          make \
            EE_CC=/usr/local/ps2dev/ee/bin/ee-gcc \
            EE_CXX=/usr/local/ps2dev/ee/bin/ee-g++ \
            EE_AR=/usr/local/ps2dev/ee/bin/ee-ar \
            EE_LD=/usr/local/ps2dev/ee/bin/ee-gcc

      - name: Upload ELF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CPS2emu-PS2-Binary
          # Search for the ELF inside the src folder where it was built
          path: |
            src/*.ELF
            src/*.elf
